### ISSUE TITLE
Example case `ff-pm/flow-over-cube-3d/` does not compile with DuMux v3.6

### ISSUE THREAD

**Issue by IshaanDesai** [precice/dumux-adapter#17]
## Description

The example case `examples/ff-pm/flow-over-cube-3d/` fails to compile as part of the test suite compilation. The error is:

```bash
/dune-modules/dumux-adapter/examples/ff-pm/flow-over-cube-3d/ffproblem-reversed.hh: In member function ‘Dumux::StokesSubProblem<TypeTag>::BoundaryTypes Dumux::StokesSubProblem<TypeTag>::boundaryTypes(const Element&, const SubControlVolumeFace&) const’:
/dune-modules/dumux-adapter/examples/ff-pm/flow-over-cube-3d/ffproblem-reversed.hh:193:20: error: ‘dataIdsWereSet_setBeaversJoseph’ was not declared in this scope
  193 |             assert(dataIdsWereSet_setBeaversJoseph);
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

### Environment

Ubuntu 22.04 LTS, preCICE 2.5.0, DuMuX 3.6, DuMuX-preCICE 1.0

## Steps to reproduce

After building the adapter, go to `dumux-adapter/build-cmake` and run `make -j1 build_tests`.
